# Generated by Django 5.2.14 on 2026-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=2048)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('naukri', 'Naukri'), ('wellfound', 'Wellfound'), ('glassdoor', 'Glassdoor')], default='linkedin', max_length=50)),
                ('platform_job_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('queued', 'Queued for Apply'), ('skipped', 'Skipped'), ('applied', 'Applied'), ('failed', 'Failed')], default='discovered', max_length=50)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_easy_apply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-relevance_score', '-created_at'],
                'unique_together': {('link', 'platform')},
            },
        ),
    ]
