# Generated by Django 5.2.14 on 2026-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('parsed_text', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('extracted_name', models.CharField(blank=True, max_length=255)),
                ('extracted_email', models.CharField(blank=True, max_length=255)),
                ('extracted_phone', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
